import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionWrapper from "../components/SessionWrapper";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/lib/store";
import { Providers } from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <SessionWrapper>
        <html lang="en">
          <body className={`${inter.className} min-h-screen`}>{children}</body>
        </html>
      </SessionWrapper>
    </Providers>
  );
}
